### ISSUE TITLE
meta.last_sync use UTC time

### ISSUE THREAD

**Issue by redshodan** [nicfit/MishMash#7]
Use UTC time for meta.last_sync and avoid the timezone nonsense.

**Comment by redshodan** [comment]
I was just about to do a simple change/PR for this, but I guess this is a bit more involved than just last_sync. the date_added, ctime, mtimes. Who knows what tzone will be involved for ctime/mtime from the local FS. the linux manpage for stat(2) doesn't say anything at all about timezone and apparently each FS does it's own tstmp marking.

Anyways, last_sync is only used (value consumed) in the info cmd. This should (untested) convert utc to local tzone for reporting it to the user.
        last_sync = meta.last_sync.replace(tzinfo=timezone.utc).astimezone(tz=None)

**Comment by nicfit** [comment]
Added in aa266a1b3895b5065ef75c4efec69cdc29221cfb
